### ISSUE TITLE
[am-gateway]The /oidc base path return the wrong URL inside the JSON

### ISSUE THREAD

**Issue by charleech** [gravitee-io/issues#1829]
The `am-management-api` is behind the `nginx` by following the [gravitee-docker/platform/nginx/nginx.conf](https://github.com/gravitee-io/gravitee-docker/blob/master/platform/nginx/nginx.conf).

``` Nginx

  upstream gio-am-mgmt-api {
    server gio-am-mgmt-api:8093;
  }
  server {
    location /am/ {
      proxy_pass http://gio-am-gateway/;
      proxy_redirect $scheme://$http_host/apim/ $scheme://$http_host/apim/;
      proxy_redirect $scheme://$http_host/ $scheme://$http_host/am/;
      proxy_cookie_path / /am;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-Server $host;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $http_host;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_set_header   X-Forwarded-Path /am;
    }
}
```
I've created the new domain named `mydomain` and access the `OpenID Connect endpoints` as mentioned at [OpenID Connect](https://docs.gravitee.io/am/2.x/am_breaking_changes_2.0.html#openid_connect). as `https://my-host:port/am/mydomain/oidc/.well-known/openid-configuration`. There is a response but missing the context path `/am`  for every `OIDC endpoint` as the following example: -

```json
{
  "issuer": "http://gravitee.am",
  "authorization_endpoint": "https://my-host:port/mydomain/oauth/authorize",
  "token_endpoint": "https://my-host:port/mydomain/oauth/token",
  "userinfo_endpoint": "https://my-host:port/mydomain/oidc/userinfo",
  "jwks_uri": "https://my-host:port/mydomain/oidc/.well-known/jwks.json",
  "end_session_endpoint": "https://my-host:port/mydomain/logout",
  "revocation_endpoint": "https://my-host:port/mydomain/oauth/revoke",
  "introspection_endpoint": "https://my-host:port/mydomain/oauth/introspect",
}
```
### Expected Behavior
The return OIDC endpoint should be respected to the context path.

### Current Behavior
There is no context path.

### Possible Solution
N/A

### Steps to Reproduce (for bugs)
1. Login to the `am-management-ui` with default `admin/adminadmin`.
2. Create the domain named `mydomain`.
3. Browse to `https://my-host:port/am/mydomain/oidc/.well-known/openid-configuration`.

### Context
I've tried to retrieve the `OpenID Connect endpoints` and evaluate the login to get the `access-token`.

### Your Environment
* Version used: 
  The docker tag `2` for all of AM component
  * graviteeio/am-gateway:2
  * graviteeio/am-management-api:2
  * graviteeio/am-management-ui:2
* Browser Name and version: 
  * Google Chrome for Windows Version `71.0.3578.98 (Official Build) (64-bit)`
* Operating System and version:
  * Based on the docker image with command inside the running container  `cat /etc/*release`
  ```
  3.8.1
  NAME="Alpine Linux"
  ID=alpine
  VERSION_ID=3.8.1
  PRETTY_NAME="Alpine Linux v3.8"
  HOME_URL="http://alpinelinux.org"
  BUG_REPORT_URL="http://bugs.alpinelinux.org"
  ```

**Comment by brasseld** [comment]
Hi @charleech 

The location you are sharing here 

```
  server {
    location /am/ {
      proxy_pass http://gio-am-gateway/;
      proxy_redirect $scheme://$http_host/apim/ $scheme://$http_host/apim/;
      proxy_redirect $scheme://$http_host/ $scheme://$http_host/am/;
      proxy_cookie_path / /am;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-Server $host;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $http_host;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_set_header   X-Forwarded-Path /am;
    }
}
```

is about the gateway, not the management...

But for sure, there is a typo:
`proxy_redirect $scheme://$http_host/apim/ $scheme://$http_host/apim/;`
to 
`proxy_redirect $scheme://$http_host/am/ $scheme://$http_host/am/;`

**Comment by brasseld** [comment]
Typo has been fixed from master branch:

https://github.com/gravitee-io/gravitee-docker/commit/ac3685ec38b3e2eb124cd0c1aacbb18b50b534a8

**Comment by charleech** [comment]
Hi @brasseld 

Thank you for your quick response.

I've change the `nginx.conf` and stop/start, together with executing the command inside the `nginx` container as `cat /etc/nginx/nginx.conf` to ensure that it is changed as the following output.

```nginx
    location /am/ {
      proxy_pass http://gio-am-gateway/;
      proxy_redirect $scheme://$http_host/am/ $scheme://$http_host/am/;
      proxy_redirect $scheme://$http_host/ $scheme://$http_host/am/;
      proxy_cookie_path / /am;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-Server $host;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $http_host;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_set_header   X-Forwarded-Path /am;
    }
```

After accessing the `https://my-host:port/am/mydomain/oidc/.well-known/openid-configuration` the context path `/am` still missing from JSON response as

```json
{
  "issuer": "http://gravitee.am",
  "authorization_endpoint": "https://my-host:port/mydomain/oauth/authorize",
  "token_endpoint": "https://my-host:port/mydomain/oauth/token",
  "userinfo_endpoint": "https://my-host:port/mydomain/oidc/userinfo",
  "jwks_uri": "https://my-host:port/mydomain/oidc/.well-known/jwks.json",
  "end_session_endpoint": "https://my-host:port/mydomain/logout",
  "revocation_endpoint": "https://my-host:port/mydomain/oauth/revoke",
  "introspection_endpoint": "https://my-host:port/mydomain/oauth/introspect",
}
```

I'm not sure if I'm doing something wrong or not. Could you please help to advise further?

**Comment by brasseld** [comment]
Ok, I will have a try today.

Did you change something from the docker compose file we are providing by default ?

**Comment by charleech** [comment]
There is no any changing, everything use the example `docker compose`, except the published `port` for the `nginx` since the `80` and `443` have been used already.

**Comment by brasseld** [comment]
Ok, I've pushed a new commit on the master branch which is resolving your issue.

Please provide your feedback / close the issue if it's ok from your side.

Cheers.

**Comment by charleech** [comment]
Thank you for your quick response. 

I can confirm that changing the  `proxy_set_header   X-Forwarded-Path /am` to `proxy_set_header   X-Forwarded-Prefix /am` solve the issue.

To summarize the proper `nginx` configuration is

```nginx
    location /am/ {
      proxy_pass http://gio-am-gateway/;
      proxy_redirect $scheme://$http_host/am/ $scheme://$http_host/am/; <--- 1
      proxy_redirect $scheme://$http_host/ $scheme://$http_host/am/;
      proxy_cookie_path / /am;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-Server $host;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $http_host;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_set_header   X-Forwarded-Prefix /am; <--- 2
    }
```

The response JSON contains the context path `/am` properly.

```json
{
  "issuer": "http://gravitee.am",
  "authorization_endpoint": "https://my-host:port/am/mydomain/oauth/authorize",
  "token_endpoint": "https://my-host:port/am/mydomain/oauth/token",
  "userinfo_endpoint": "https://my-host:port/am/mydomain/oidc/userinfo",
  "jwks_uri": "https://my-host:port/mydomain/am/oidc/.well-known/jwks.json",
  "end_session_endpoint": "https://my-host:port/am/mydomain/logout",
  "revocation_endpoint": "https://my-host:port/am/mydomain/oauth/revoke",
  "introspection_endpoint": "https://my-host:port/am/mydomain/oauth/introspect",
}
```
