### ISSUE TITLE
[gateway] conditional logging on Application prevents to display API logs

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7329]
## :collision: Describe the bug
When enabling logging on an API with a Condition on an Application, the detailed logs are not displayed and the following error is raise in the gateway logs : 

```
[vert.x-eventloop-thread-10] [] WARN  i.g.g.c.l.c.e.ExpressionLanguageBasedConditionEvaluator - Error parsing condition {#context.application == '544c99ac-b788-428e-8c99-acb788f28e92'}
io.gravitee.el.exceptions.ExpressionEvaluationException: The template evaluation returns an error. Expression:
#context.application == '544c99ac-b788-428e-8c99-acb788f28e92'
 	at io.gravitee.el.spel.SpelTemplateEngine.getValue(SpelTemplateEngine.java:62)
 	at io.gravitee.el.spel.SpelTemplateEngine.getValue(SpelTemplateEngine.java:68)
 	at io.gravitee.gateway.core.logging.condition.el.ExpressionLanguageBasedConditionEvaluator.evaluate(ExpressionLanguageBasedConditionEvaluator.java:43)
 	at io.gravitee.gateway.core.logging.condition.el.ExpressionLanguageBasedConditionEvaluator.evaluate(ExpressionLanguageBasedConditionEvaluator.java:29)
 	at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.evaluate(LoggableRequestProcessor.java:76)
 	at io.gravitee.gateway.handlers.api.processor.logging.ApiLoggableRequestProcessor.evaluate(ApiLoggableRequestProcessor.java:40)
...
 Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'application' cannot be found on object of type 'io.gravitee.gateway.reactor.handler.context.EvaluableExecutionContext' - maybe not public or not valid?
 	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:217)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:104)
 	at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:51)
```

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create an API with API Key Plan
2. subscribe to it with your Default Application
3. Enable Logging on the API and add a Condition on the Default Application using the Condition wizard (using the pen next to the field)
4. Make a reuest on the API and check the logs 

⚠️ According to https://github.com/gravitee-io/issues/issues/7329#issuecomment-1078807821, it breaks upgrade, so it was working for previous versions

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: replicated in 3.15.5, 3.16.0 and 3.16.1

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
@apoddany can you check with `context.attributes.application` ?

**Comment by apoddany** [comment]
@mouligno : 
```
gio_apim_gateway-3.15.5 | 15:02:47.434 [vert.x-eventloop-thread-8] [] WARN  i.g.g.c.l.c.e.ExpressionLanguageBasedConditionEvaluator - Error parsing condition {#context.attributes.application == '544c99ac-b788-428e-8c99-acb788f28e92'}
gio_apim_gateway-3.15.5 | io.gravitee.el.exceptions.ExpressionEvaluationException: The template evaluation returns an error. Expression:
gio_apim_gateway-3.15.5 | #context.attributes.application == '544c99ac-b788-428e-8c99-acb788f28e92'
gio_apim_gateway-3.15.5 | 	at io.gravitee.el.spel.SpelTemplateEngine.getValue(SpelTemplateEngine.java:62)
gio_apim_gateway-3.15.5 | 	at io.gravitee.el.spel.SpelTemplateEngine.getValue(SpelTemplateEngine.java:68)
```

**Comment by mouligno** [comment]
As discussed with @apoddany, an exception is raised but the logs is correctly stored and displayed.

**Comment by ytvnr** [comment]
@apoddany @mouligno the syntax is not correct, the good one is: `{#context.attributes['application'] == '544c99ac-b788-428e-8c99-acb788f28e92'}`

**Comment by ytvnr** [comment]
Tested with two applications which has subscribed to my api, I have the logs only for the application I choose in the condition.
@apoddany I put it in `To test` and assign it to you.

**Comment by apoddany** [comment]
@ytvnr the concern here is when using the "Conditional Logging Editor", it will keep the wrong syntax. In addition when upgrading from previous versions, it will break.

**Comment by gcusnieux** [comment]
Hi @a-cordier @ytvnr, Recently I added a feat to gv-expressionlanguage to support access to attributes with dot. 
See https://github.com/gravitee-io/gravitee-expression-language/commit/384d23cc8ae70f507c1241ad32359f944f2b0360
Normally this should be fixed with APIM 3.15.6

**Comment by RubenMMSantos** [comment]
Issue confirmed as fixed and working as expected
condition used for conditional logging:
![Screenshot 2022-04-06 at 15.52.16.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/41e74e90-1410-4d87-a6b4-039fdc3e46df)
Example of the logs working
![Screenshot 2022-04-06 at 15.51.34.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/c51de027-0b50-45b1-9042-cdb22b443afc)

**Comment by gaetanmaisse** [comment]
<img width="1813" alt="image" src="https://user-images.githubusercontent.com/4112568/165937178-57e2940a-ea41-4230-b014-ca606bc7b458.png">
I'm still seeing the issue on our `3.15` env
